import os

QUALTRICS_API_TOKEN = os.getenv("QUALTRICS_API_TOKEN")
QUALTRICS_DATACENTER = os.getenv("QUALTRICS_DATA_CENTER")
SURVEY_ID = os.getenv("QUALTRICS_SURVEY_ID")

DB_PATH = "data/qualtrics.db"
LOG_DIR = "logs"

POLL_INTERVAL_SECONDS = 60

TIMEOUT_EXPORT_START = 30
TIMEOUT_STATUS_CHECK = 30
TIMEOUT_FILE_DOWNLOAD = 60
